# Generated by Django 4.0.5 on 2022-07-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinturas',
            name='aprobada',
            field=models.BooleanField(default=False, verbose_name='aprobada'),
        ),
        migrations.AlterField(
            model_name='pinturas',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='destacado'),
        ),
    ]
