# Generated by Django 4.0.5 on 2022-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinturas',
            name='idPintura',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id pintura'),
        ),
    ]
