# Generated by Django 4.0.5 on 2022-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pinturas_idpintura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='idAutor',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id Autor'),
        ),
    ]
