# Generated by Django 4.0.5 on 2022-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categoria_idcategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinturas',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
