# Generated by Django 4.0.5 on 2022-07-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoria_pinturas_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinturas',
            name='categoria',
        ),
    ]
