# Generated by Django 4.0.5 on 2022-07-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_pinturas_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinturas',
            name='categoria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
