# Generated by Django 4.0.5 on 2022-07-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
